#!/usr/bin/env python

import argparse

from hydrabus_framework.core.engine import HydraFramework


__author__ = "Jordan Ovrè <ghecko78@gmail.com>"


def welcome():
    """
    Print framework header
    :return:
    """
    print("""\033[92m
      _    ___     _______  _____            ____  _    _  _____           
     | |  | \ \   / /  __ \|  __ \     /\   |  _ \| |  | |/ ____|          
     | |__| |\ \_/ /| |  | | |__) |   /  \  | |_) | |  | | (___            
     |  __  | \   / | |  | |  _  /   / /\ \ |  _ <| |  | |\___ \           
     | |  | |  | |  | |__| | | \ \  / ____ \| |_) | |__| |____) |          
     |_|__|_|__|_|  |_____/|_|__\_\/_/____\_\____/ \____/|_____/____  _  __
     |  ____|  __ \     /\   |  \/  |  ____\ \        / / __ \|  __ \| |/ /
     | |__  | |__) |   /  \  | \  / | |__   \ \  /\  / / |  | | |__) | ' / 
     |  __| |  _  /   / /\ \ | |\/| |  __|   \ \/  \/ /| |  | |  _  /|  <  
     | |    | | \ \  / ____ \| |  | | |____   \  /\  / | |__| | | \ \| . \ 
     |_|    |_|  \_\/_/    \_\_|  |_|______|   \/  \/   \____/|_|  \_\_|\_\\
 
    \033[0m""")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-s', '--file', help='A file containing framework commands\' (one per line)')
    args = parser.parse_args()
    welcome()
    instance = HydraFramework()
    instance.run(args.file)

